name: Beautiful Garden
on:
  schedule:
    - cron: '0 12 * * *' # Updates daily at noon UTC
  workflow_dispatch:

jobs:
  update-garden:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: pip install PyGithub python-dateutil numpy
      
      - name: Create garden script
        run: |
          mkdir -p .github/scripts
          cat << 'EOF' > .github/scripts/garden.py
          # [PASTE THE FULL PYTHON SCRIPT FROM BELOW HERE]
          EOF
      
      - name: Generate beautiful garden
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python .github/scripts/garden.py
      
      - name: Commit and push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "🌸 Updated beautiful garden"
          git push
