name: Beautiful Garden
on:
  workflow_dispatch:

jobs:
  update-garden:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: pip install PyGithub python-dateutil numpy
      
      - name: Create garden script
        run: |
          mkdir -p .github/scripts
          cat << 'EOF' > .github/scripts/garden.py
          import os
          import math
          import numpy as np
          from datetime import datetime, timedelta
          from github import Github

          COLORS = {
              'background': '#F9F7F7',
              'ground': '#DBE2EF',
              'code': '#A6E3E9',
              'issues': '#FFC4C4',
              'reviews': '#C9B6E4',
              'text': '#3F3F44'
          }

          def get_contributions():
              g = Github(os.getenv('GH_TOKEN'))
              user = g.get_user(os.getenv('GITHUB_ACTOR'))
              events = user.get_public_events()
              counts = {'code': 0, 'issues': 0, 'reviews': 0}
              for event in events:
                  if event.type in ['PushEvent', 'CreateEvent']: counts['code'] += 1
                  elif event.type in ['IssuesEvent', 'IssueCommentEvent']: counts['issues'] += 1
                  elif event.type in ['PullRequestReviewEvent', 'PullRequestReviewCommentEvent']: counts['reviews'] += 1
              return counts

          def generate_svg(data):
              svg = f'''
              <svg width="400" height="250" xmlns="http://www.w3.org/2000/svg">
                  <rect width="100%" height="100%" fill="{COLORS['background']}"/>
                  <text x="50%" y="30" font-family="Arial" text-anchor="middle">Beautiful Garden</text>
                  <circle cx="100" cy="100" r="40" fill="{COLORS['code']}"/>
                  <circle cx="200" cy="120" r="30" fill="{COLORS['issues']}"/>
                  <circle cx="300" cy="
